
def symbol_to_vdw(symbol):
	""" 
	extract from https://en.wikipedia.org/wiki/Atomic_radii_of_the_elements_(data_page)
	vdw radii values in A
	"""
	vdwdic = {"H":	1.2,
	"He":	1.4,
	"Li":	1.82,
	"Be":	1.53,
	"B":	1.92,
	"C":	1.7,
	"N":	1.55,
	"O":	1.52,
	"F":	1.47,
	"Ne":	1.54,
	"Na":	2.27,
	"Mg":	1.73,
	"Al":	1.84,
	"Si":	2.1,
	"P":	1.8,
	"S":	1.8,
	"Cl":	1.75,
	"Ar":	1.88,
	"K":	2.75,
	"Ca":	2.31,
	"Sc":	2.11,
	"Ti":	None ,
	"V":	None ,
	"Cr":	None ,
	"Mn":	None ,
	"Fe":	None ,
	"Co":	None ,
	"Ni":	1.63,
	"Cu":	1.4,
	"Zn":	1.39,
	"Ga":	1.87,
	"Ge":	2.11,
	"As":	1.85,
	"Se":	1.9,
	"Br":	1.85,
	"Kr":	2.02,
	"Rb":	3.03,
	"Sr":	2.49,
	"Y":	None ,
	"Zr":	None ,
	"Nb":	None ,
	"Mo":	None ,
	"Tc":	None ,
	"Ru":	None ,
	"Rh":	None ,
	"Pd":	1.63,
	"Ag":	1.72,
	"Cd":	1.58,
	"In":	1.93,
	"Sn":	2.17,
	"Sb":	2.06,
	"Te":	2.06,
	"I":	1.98,
	"Xe":	2.16,
	"Cs":	3.43,
	"Ba":	2.68,
	"La":	None ,
	"Ce":	None ,
	"Pr":	None ,
	"Nd":	None ,
	"Pm":	None ,
	"Sm":	None ,
	"Eu":	None ,
	"Gd":	None ,
	"Tb":	None ,
	"Dy":	None ,
	"Ho":	None ,
	"Er":	None ,
	"Tm":	None ,
	"Yb":	None ,
	"Lu":	None ,
	"Hf":	None ,
	"Ta":	None ,
	"W":	None ,
	"Re":	None ,
	"Os":	None ,
	"Ir":	None ,
	"Pt":	1.75,
	"Au":	1.66,
	"Hg":	1.55,
	"Tl":	1.96,
	"Pb":	2.02,
	"Bi":	2.07,
	"Po":	1.97,
	"At":	2.02,
	"Rn":	2.2,
	"Fr":	3.48,
	"Ra":	2.83,
	"Ac":	None ,
	"Th":	None ,
	"Pa":	None ,
	"U":	1.86,
	"Np":	None ,
	"Pu":	None ,
	"Am":	None ,
	"Cm":	None ,
	"Bk":	None ,
	"Cf":	None ,
	"Es":	None ,
	"Fm":	None ,
	"Md":	None ,
	"No":	None ,
	"Lr":	None ,
	"Rf":	None ,
	"Db":	None ,
	"Sg":	None ,
	"Bh":	None ,
	"Hs":	None ,
	"Mt":	None ,
	"Ds":	None ,
	"Rg":	None ,
	"Cn":	None ,
	"Nh":	None ,
	"Fl":	None ,
	"Mc":	None ,
	"Lv":	None ,
	"Ts":	None ,
	"Og":	None ,
	}
	try:
		vdwradius = vdwdic[symbol]
		if vdwradius == None:
			print "vdw radius of %s is not defined. Please check this value."%(symbol)
			return 0
		else:
			return vdwradius
	except:
		return "There is an error in the atom symbol %s. Please check this."%(symbol)

